### ISSUE TITLE
Could not load class

### ISSUE THREAD

**Issue by BigBlockStudios** [sepiariver/recaptchav2#26] opened 2018-04-23 18:59 UTC
does not work at all,  it seems that it is looking for the recaptchav2 class within the formit model folder, 

[2018-04-23 14:50:46] (ERROR @ /var/www/vhosts/domain.ca/core/components/formit/src/FormIt/Request.php : 203) [FormIt] /var/www/vhosts/domain.ca/core/components/formit/model/
[2018-04-23 14:50:46] (ERROR @ /var/www/vhosts/domain.ca/core/components/formit/src/FormIt/Request.php : 87) [FormIt] Could not load FormItReCaptcha service class.

**Comment by pashajanx** [comment] 2018-04-24 17:18
After updating the FormIt the same problem

**Comment by damreywil** [comment] 2018-04-24 17:47
Seeing same error log entries on multiple sites now after updating FormIt to 4.0.0-pl.

`[2018-04-24 17:26:48] (ERROR @ /var/www/vhosts/domain.com/stage.domain.com/core/components/formit/src/FormIt/Request.php : 87) [FormIt] Could not load FormItReCaptcha service class.`

- MODX Revolution [2.6.2-pl]
- FormIt [4.0.0-pl]
- ReCaptchaV2 [2.3.0-rc1]

**Comment by BigBlockStudios** [comment] 2018-04-24 18:10
I did not test (or update other sites) to formit 4, but this particular one was updated to formit 4.

**Comment by elz64** [comment] 2018-05-25 13:20
same here:
`httpdocs/core/components/formit/src/FormIt/Request.php : 87) [FormIt] Le service ReCaptcha n'a pas pu charger la classe`
modx2.6.3 /formit-4.0.1-pl

**Comment by xceed-will** [comment] 2018-07-30 06:00
same here: core/components/formit/src/FormIt/Request.php : 87) [FormIt] Could not load FormItReCaptcha service class.

**Comment by hitodev** [comment] 2018-08-31 10:36
Same:
[2018-08-31 12:41:54] (ERROR @ /var/www/xxx/xxx/xxx/xxx/xxx/components/formit/src/FormIt/Request.php : 87) [FormIt] Le service ReCaptcha n'a pas pu charger la classe.
 
MODX Revolution 2.6.5-pl + Formit 4.1.0-pl + reCaptchav2 2.3.0-rc1

**Comment by sepiariver** [comment] 2018-11-03 07:05
Duplicate of https://github.com/sepiariver/recaptchav2/issues/27 related to FormIt bug

**Closed as completed by sepiariver** 2018-11-03 07:05 UTC
